## 配置参考：https://docs.spring.io/spring-boot/docs/3.2.5/reference/html/features.html#features.logging

# 系统监控配置
management:
  endpoints:
    web:
      exposure:
        include: [ "health","info","metrics","prometheus" ]

# Spring 配置
spring:
  profiles:
    active: dev
  messages:
    # 这里声明 MessageSource 加载的国际化消息文件列表，以逗号 (,) 分割
    basename: i18n.messages,org.springframework.security.messages
    fallback-to-system-locale: false
  cache:
    redis:
      key-prefix: "cache:"
      enable-statistics: true
      time-to-live: 1h
  sql:
    init:
      mode: always
      continue-on-error: false
  #      TODO 提供一次性初始化脚本，避免每次删除数据表
  #      schema-locations:
  #        - "classpath:org/quartz/impl/jdbcjobstore/tables_mysql_innodb.sql"
  datasource:
    hikari:
      minimum-idle: 5
      maximum-pool-size: 15
      auto-commit: true
      idle-timeout: 30000
      pool-name: hikariCP
      max-lifetime: 30000
      connection-timeout: 30000
      connection-test-query: SELECT 1
  jpa:
    hibernate:
      ddl-auto: update
  #  TODO 未来开发灵活的调度任务系统，支持后台管理界面
  #  quartz:
  #    job-store-type: jdbc
  #    startup-delay: 30s
  data:
    rest:
      base-path: /api
      enable-enum-translation: true
  mvc:
    format:
      date: "yyyy-MM-dd"
      time: "HH:mm:ss"
      date-time: "yyyy-MM-dd HH:mm:ss"

# 项目配置
rowing:
  security:
    login-path: "/login"
    logout-path: "/logout"
    register-path: "/register"
    ignore-path:
    public-path:
      - ${rowing.security.register-path}
      - "/error"
      - "/error/**"
    basic-path:
      - "/actuator"
      - "/actuator/**"
