# Spring 配置
spring:
  profiles:
    active: dev
  messages:
    # 这里声明 MessageSource 加载的国际化消息文件列表，以逗号 (,) 分割
    basename: i18n.messages,org.springframework.security.messages
    fallback-to-system-locale: false
  cache:
    redis:
      key-prefix: "rowing:"
      enable-statistics: true
      time-to-live: 1h
  jpa:
    hibernate:
      ddl-auto: update
  sql:
    init:
      mode: always
      continue-on-error: true
  datasource:
    hikari:
      minimum-idle: 5
      maximum-pool-size: 15
      auto-commit: true
      idle-timeout: 30000
      pool-name: hikariCP
      max-lifetime: 30000
      connection-timeout: 30000
      connection-test-query: SELECT 1
  data:
    rest:
      base-path: /api
      enable-enum-translation: true

# 项目配置
rowing:
  security:
    login-path: "/login"
    logout-path: "/logout"
    register-path: "/register"
    ignore-path:
    public-path:
      - "/error"
      - "/error/**"
