# Tomcat 配置
server:
  port: 80

# 日志配置
logging:
  level:
    ROOT: INFO
    web: INFO
    org.hibernate.orm.jdbc.bind: INFO
    sql: INFO
    rowing: INFO
    org.springframework.security: INFO
  file:
    name: application-test.log
    path: ./logs
  logback:
    rollingpolicy:
      # 默认最大历史 7
      max-history: 7
      # 默认单文件 10MB
      max-file-size: 10MB
      total-size-cap: 1GB

# Spring 配置
spring:
  application:
    name: "Rowing Prod"
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/rowing?serverTimezone=Asia/Shanghai&characterEncoding=utf8&useUnicode=true&useSSL=false&allowMultiQueries=true
    username: root
    password: 123456
  data:
    redis:
      client-type: lettuce
      database: 0
      host: 127.0.0.1
      password: 123456
      connect-timeout: 10s
  # 账户中心是需要会话的，但不需要 Cookie 自动登录
  session:
    # 1 hour
    timeout: 3600
  security:
    user:
      name: user
      password: 123456
      roles:
        - BASIC

# 验证码配置
kaptcha:
  enabled: true
  config:
    kaptcha:
      border: "no"
      image:
        width: "150"
        height: "40"
      textproducer:
        font:
          color: "black"
          size: "30"
        char:
          space: "5"
          length: 4
  parameter: "kaptcha"

# 项目配置
rowing:
  okhttp:
    cache-path: ${user.dir}/.cache
    cache-max-size: 1GB
    call-timeout: 5s
    logging-level: BASIC
